/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import domain.ZaposleniUBaru;
import javax.swing.JFrame;
import static javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE;

/**
 *
 * @author Djapac
 */
public class FrmMain extends javax.swing.JFrame {

    ZaposleniUBaru prijavljenZaposleni;
    
    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        initComponents();
        setTitle("Lokal");
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        setLocationRelativeTo(null);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    FrmMain(ZaposleniUBaru zap) {
        initComponents();
        setTitle("Lokal");
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        setLocationRelativeTo(null);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.prijavljenZaposleni = zap;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnIzadji = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmiKreiranjeKorisnika = new javax.swing.JMenuItem();
        jmiPretrazivanjeKorisnika = new javax.swing.JMenuItem();
        jmiBrisanjeKorisnika = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmiKreiranjeStola = new javax.swing.JMenuItem();
        jmiPretrazivanjeStola = new javax.swing.JMenuItem();
        jmiIzmenaPodatakaOStolu = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jmiKreiranjeRezervacije = new javax.swing.JMenuItem();
        jmiBrisanjeRez = new javax.swing.JMenuItem();
        jmiIzmenaRez = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnIzadji.setText("IZAĐI");
        btnIzadji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzadjiActionPerformed(evt);
            }
        });

        jMenu1.setText("Korisnik");

        jmiKreiranjeKorisnika.setText("Kreiranje novog korisnika");
        jmiKreiranjeKorisnika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiKreiranjeKorisnikaActionPerformed(evt);
            }
        });
        jMenu1.add(jmiKreiranjeKorisnika);

        jmiPretrazivanjeKorisnika.setText("Pretraživanje novog korisnika");
        jmiPretrazivanjeKorisnika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPretrazivanjeKorisnikaActionPerformed(evt);
            }
        });
        jMenu1.add(jmiPretrazivanjeKorisnika);

        jmiBrisanjeKorisnika.setText("Brisanje korisnika");
        jmiBrisanjeKorisnika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiBrisanjeKorisnikaActionPerformed(evt);
            }
        });
        jMenu1.add(jmiBrisanjeKorisnika);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Sto");

        jmiKreiranjeStola.setText("Kreiranje stola");
        jmiKreiranjeStola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiKreiranjeStolaActionPerformed(evt);
            }
        });
        jMenu2.add(jmiKreiranjeStola);

        jmiPretrazivanjeStola.setText("Pretraživanje stola");
        jmiPretrazivanjeStola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPretrazivanjeStolaActionPerformed(evt);
            }
        });
        jMenu2.add(jmiPretrazivanjeStola);

        jmiIzmenaPodatakaOStolu.setText("Izmena podataka o stolu");
        jmiIzmenaPodatakaOStolu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiIzmenaPodatakaOStoluActionPerformed(evt);
            }
        });
        jMenu2.add(jmiIzmenaPodatakaOStolu);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Rezervacija");

        jmiKreiranjeRezervacije.setText("Kreiranje rezervacije");
        jmiKreiranjeRezervacije.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiKreiranjeRezervacijeActionPerformed(evt);
            }
        });
        jMenu3.add(jmiKreiranjeRezervacije);

        jmiBrisanjeRez.setText("Pretraživanje rezervacije");
        jmiBrisanjeRez.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiBrisanjeRezActionPerformed(evt);
            }
        });
        jMenu3.add(jmiBrisanjeRez);

        jmiIzmenaRez.setText("Izmena rezervacije");
        jmiIzmenaRez.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiIzmenaRezActionPerformed(evt);
            }
        });
        jMenu3.add(jmiIzmenaRez);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(216, Short.MAX_VALUE)
                .addComponent(btnIzadji, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(205, Short.MAX_VALUE)
                .addComponent(btnIzadji, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIzadjiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzadjiActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnIzadjiActionPerformed

    private void jmiBrisanjeRezActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiBrisanjeRezActionPerformed
        // TODO add your handling code here:
        new FrmPretragaRezervacije().setVisible(true);
        
    }//GEN-LAST:event_jmiBrisanjeRezActionPerformed

    private void jmiKreiranjeKorisnikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiKreiranjeKorisnikaActionPerformed
        // TODO add your handling code here:
        new FrmKreirajKorisnika().setVisible(true);
        
    }//GEN-LAST:event_jmiKreiranjeKorisnikaActionPerformed

    private void jmiKreiranjeStolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiKreiranjeStolaActionPerformed
        // TODO add your handling code here:
        new FrmKreirajSto().setVisible(true);
        
    }//GEN-LAST:event_jmiKreiranjeStolaActionPerformed

    private void jmiPretrazivanjeKorisnikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPretrazivanjeKorisnikaActionPerformed
        // TODO add your handling code here:
        new FrmPretragaKorisnika().setVisible(true);
        
    }//GEN-LAST:event_jmiPretrazivanjeKorisnikaActionPerformed

    private void jmiPretrazivanjeStolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPretrazivanjeStolaActionPerformed
        // TODO add your handling code here:
        new FrmPretragaStola().setVisible(true);
        
    }//GEN-LAST:event_jmiPretrazivanjeStolaActionPerformed

    private void jmiKreiranjeRezervacijeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiKreiranjeRezervacijeActionPerformed
        // TODO add your handling code here:
        new FrmKreirajRezervaciju(prijavljenZaposleni).setVisible(true);
    }//GEN-LAST:event_jmiKreiranjeRezervacijeActionPerformed

    private void jmiIzmenaRezActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiIzmenaRezActionPerformed
        // TODO add your handling code here:
        new FrmPretragaRezervacije().setVisible(true);
        
    }//GEN-LAST:event_jmiIzmenaRezActionPerformed

    private void jmiBrisanjeKorisnikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiBrisanjeKorisnikaActionPerformed
        // TODO add your handling code here:
        new FrmPretragaKorisnika().setVisible(true);
    }//GEN-LAST:event_jmiBrisanjeKorisnikaActionPerformed

    private void jmiIzmenaPodatakaOStoluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiIzmenaPodatakaOStoluActionPerformed
        // TODO add your handling code here:
        new FrmPretragaStola().setVisible(true);
    }//GEN-LAST:event_jmiIzmenaPodatakaOStoluActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzadji;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jmiBrisanjeKorisnika;
    private javax.swing.JMenuItem jmiBrisanjeRez;
    private javax.swing.JMenuItem jmiIzmenaPodatakaOStolu;
    private javax.swing.JMenuItem jmiIzmenaRez;
    private javax.swing.JMenuItem jmiKreiranjeKorisnika;
    private javax.swing.JMenuItem jmiKreiranjeRezervacije;
    private javax.swing.JMenuItem jmiKreiranjeStola;
    private javax.swing.JMenuItem jmiPretrazivanjeKorisnika;
    private javax.swing.JMenuItem jmiPretrazivanjeStola;
    // End of variables declaration//GEN-END:variables
}
