/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import domain.Sto;
import domain.ZaposleniUBaru;
import java.util.List;
import javax.swing.JOptionPane;
import logic.Controller;
import model.ModelTabeleStolovi;

/**
 *
 * @author Djapac
 */
public class FrmPretragaStola extends javax.swing.JFrame {

    FrmKreirajRezervaciju frmRez;
    /**
     * Creates new form FrmPretragaStola
     */
    public FrmPretragaStola() {
        initComponents();
        setTitle("Pretraga stola");
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        setLocationRelativeTo(null);
        popuniTabelu();
        btnIzaberi.setEnabled(false);
        btnDetalji.setEnabled(false);
    }

    FrmPretragaStola(FrmKreirajRezervaciju aThis) {
        initComponents();
        setTitle("Pretraga stola");
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        setLocationRelativeTo(null);
        popuniTabelu();
        this.frmRez = aThis;
        btnDetalji.setEnabled(false);
        btnIzaberi.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtRB = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSto = new javax.swing.JTable();
        btnPretraga = new javax.swing.JButton();
        btnIzadji = new javax.swing.JButton();
        btnPonisti = new javax.swing.JButton();
        btnDetalji = new javax.swing.JButton();
        btnIzaberi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Unesite redni broj stola: ");

        tblSto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblSto);

        btnPretraga.setText("Pretraži sto");
        btnPretraga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretragaActionPerformed(evt);
            }
        });

        btnIzadji.setText("Izađi");
        btnIzadji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzadjiActionPerformed(evt);
            }
        });

        btnPonisti.setText("Poništi pretragu");
        btnPonisti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPonistiActionPerformed(evt);
            }
        });

        btnDetalji.setText("Detalji");
        btnDetalji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetaljiActionPerformed(evt);
            }
        });

        btnIzaberi.setText("Izaberi");
        btnIzaberi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzaberiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(txtRB, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPretraga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnIzadji, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                            .addComponent(btnPonisti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDetalji, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnIzaberi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPonisti, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDetalji, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnIzaberi, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnIzadji, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIzadjiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzadjiActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnIzadjiActionPerformed

    private void btnPretragaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretragaActionPerformed
        // TODO add your handling code here:
        try {
            String rbStolaTekst = txtRB.getText().trim();
            Sto sto = new Sto();
            
            if(rbStolaTekst.isEmpty()){
                JOptionPane.showMessageDialog(this, "Unesite parametar za pretragu!");
                return;
            }
            if(!rbStolaTekst.matches("\\d+")){
                JOptionPane.showMessageDialog(this, "Niste uneli isključivo cifre!");
                return;
            }
            
            int brojStola = Integer.parseInt(rbStolaTekst);
            sto.setBrojStola(brojStola);
            
            
            btnPonisti.setEnabled(true);
            btnIzadji.setEnabled(true);
            btnDetalji.setEnabled(true);
            btnIzaberi.setEnabled(true);
            
            List <Sto> lista = Controller.getInstance().searchTables(sto);

            
            popuniTabelu(lista);
            JOptionPane.showMessageDialog(this, "Sistem je našao sto prema zadatoj vrednosti!","Pretraga stola", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne može da nađe sto prema zadatoj vrednosti!","Pretraga stola", JOptionPane.INFORMATION_MESSAGE);
            podesiDugmice();
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnPretragaActionPerformed

    private void btnPonistiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPonistiActionPerformed
        // TODO add your handling code here:
        popuniTabelu();
    }//GEN-LAST:event_btnPonistiActionPerformed

    private void btnDetaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetaljiActionPerformed
        // TODO add your handling code here:
        try{
        ModelTabeleStolovi mts = (ModelTabeleStolovi) tblSto.getModel();
        int red = tblSto.getSelectedRow();
       if(red!=-1){
            Sto sto = mts.getSto(red);
            JOptionPane.showMessageDialog(this, "Sistem je učitao odabran sto!", "Sto", JOptionPane.INFORMATION_MESSAGE);
            new FrmIzmeniSto(sto).setVisible(true);
           //  new FrmUnosKnjige(knjiga).setVisible(true);
            }
        else{
            JOptionPane.showMessageDialog(this, "Sistem ne može da učita podatke o odabranom stolu!", "Greška", JOptionPane.ERROR_MESSAGE);
        }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Sistem ne može da učita podatke o odabranom stolu!", "Greška", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnDetaljiActionPerformed

    private void btnIzaberiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzaberiActionPerformed
        // TODO add your handling code here:
        try {
            int red = tblSto.getSelectedRow();
            ModelTabeleStolovi mts = (ModelTabeleStolovi) tblSto.getModel();
            
            if (red != -1) {
                Sto sto = mts.getSto(red);
                frmRez.refreshTabelu(sto);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Sistem ne može da učita podatke o odabranom stolu!", "Pretraga stola", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne može da učita podatke o odabranom stolu", "Greška", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnIzaberiActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetalji;
    private javax.swing.JButton btnIzaberi;
    private javax.swing.JButton btnIzadji;
    private javax.swing.JButton btnPonisti;
    private javax.swing.JButton btnPretraga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSto;
    private javax.swing.JTextField txtRB;
    // End of variables declaration//GEN-END:variables

    private void popuniTabelu() {
        btnPonisti.setEnabled(false);
        btnPretraga.setEnabled(true);
        btnDetalji.setEnabled(false);
        btnIzaberi.setEnabled(false);
        
        txtRB.setText(" ");
        
        try {
            List<Sto> lista = Controller.getInstance().getAllTables();   
            ModelTabeleStolovi mts = new ModelTabeleStolovi(lista);
            tblSto.setModel(mts);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Niste popunili tabelu");
            ex.printStackTrace();
        }
        
        
    }

    private void popuniTabelu(List<Sto> lista) {
        try {
             ModelTabeleStolovi mts = new ModelTabeleStolovi();
             mts.refresh(lista);
            tblSto.setModel(mts);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Niste popunili tabelu");
            ex.printStackTrace();
        }
    }

    private void podesiDugmice() {
        btnPonisti.setEnabled(false);
      
    }
}
